import { Inter } from 'next/font/google';
import './globals.css';
//import "../../node_modules/bootstrap/dist/js/bootstrap";
//import "../../node_modules/bootstrap/dist/css/bootstrap";
import "bootstrap/dist/css/bootstrap.css";
//import "bootstrap/dist/js/bootstrap";

import Providers from './store/Features/providerComponent';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const RootLayout = ({ children }) => {
  return (
 
      <html lang="en">
      <body className={inter.className}
      >
        <Providers>
          {children}
        </Providers>
        </body>
      </html>

  );
};

export default RootLayout;
